version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-jessie-browsers
    steps:
      - checkout
      - run: echo "Hello World!!" > /tmp/helloworld.txt
    
      - store_artifacts:
          path: /tmp/helloworld.txt
