version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run: echo "Hello World!!" > /tmp/helloworld.txt
    
      - store_artifacts:
      path: /tmp/helloworld.txt
